services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    ports:
      - 8000:8000
    ## Disable hosting of DB on mounted volume, as this could cause database corruption.
    ## For the current deployment, database persistence is not really needed anyway.
    #command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    #volumes:
    #  - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

  dynamodb-setup:
    image: banst/awscli
    depends_on:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: "fakeMyKeyId"
      AWS_SECRET_ACCESS_KEY: "fakeSecretAccessKey"
      AWS_DEFAULT_REGION: "fakeRegion"
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
    volumes:
      - ./scripts:/home/dynamodb-setup/scripts
    working_dir: /home/dynamodb-setup
    entrypoint: /bin/sh
    command: ./scripts/init_tables.sh

  sokobubble-hof:
    image: sokobubble-hof
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/backend
    tty: true
    ports:
      - 8080:5000
    depends_on:
      dynamodb:
        condition: service_started
      dynamodb-setup:
        condition: service_completed_successfully
    environment:
      AWS_ACCESS_KEY_ID: "fakeMyKeyId"
      AWS_SECRET_ACCESS_KEY: "fakeSecretAccessKey"
      AWS_DEFAULT_REGION: "fakeRegion"
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
      FLASK_APP: "LocalGateway.py"
    # command: tail -f /dev/null
