### Get default (global) Hall of Fame (deprecated)

GET {{hall_of_fame_url}}?key=id HTTP/1.1
content-type: application/json

### Get custom Hall of Fame, by ID (deprecated)

GET {{hall_of_fame_url}}?id=custom&key=id HTTP/1.1
content-type: application/json

### Get default (global) Hall of Fame

GET {{query_url}} HTTP/1.1
content-type: application/json

### Get custom Hall of Fame

GET {{query_url}}?id=custom HTTP/1.1
content-type: application/json

### Get player scores from default (global) table

GET {{query_url}}?name=hacker HTTP/1.1
content-type: application/json

### Get player scores from custom table

GET {{query_url}}?name=hacker&id=custom HTTP/1.1
content-type: application/json

### Sub-optimal global entry for Level 1

POST {{level_completion_url}} HTTP/1.1
content-type: application/json

{
    "player": "alice",
    "level": 1,
    "levelId": 1,
    "moveCount": 27,
    "moveHistory": "u2rld4r3l3u4r2d2u2r2d"
}

### Optimal global entry for Level 1

POST {{level_completion_url}} HTTP/1.1
content-type: application/json

{
    "player": "bob",
    "level": 1,
    "levelId": 1,
    "moveCount": 23,
    "moveHistory": "u2r2d2u2r2dul4d4r3"
}

### Sub-optimal custom entry for Level 2

POST {{level_completion_url}} HTTP/1.1
content-type: application/json

{
    "player": "alice",
    "level": 2,
    "levelId": 2,
    "moveCount": 27,
    "moveHistory": "u2d4u3r2d2l3ru3d3l2u2",
    "tableId": "custom"
}